version: '3'
services:
  web_ig:
    build: ./ig
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./ig:/opt/app/
    ports:
      - "3000:3000"
    depends_on: 
      - pg_db
  pg_db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"